Update publish-script for mac

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -15,7 +15,8 @@ done
 
 errors=0
 # Ensure changes are committed
-if [[ $(git status -s) ]]; then
+git status &>/dev/null
+if [[ $? -ne 0 ]]; then
 	echo "Error: Make sure working tree is clean before publishing"
 	errors=1
 fi
@@ -34,7 +35,8 @@ echo "Publishing..."
 
 echo "Making sure local branch is up to date..."
 git pull
-if [[ $(git status -s) ]]; then
+git status &>/dev/null
+if [[ $? -ne 0 ]]; then
 	echo "Error: Fast-Forward failed. Fix any conflicts and publish again"
 	exit 1
 fi
@@ -43,9 +45,9 @@ echo "Creating temporary branch..."
 git checkout -b gh-pages
 
 echo "Generating static files..."
-python freezer.py
+python3 freezer.py
 if [[ $? -ne 0 ]]; then
-	echo "Failed to build, have you setup the environment."
+	echo "Failed to build, have you setup the environment?"
 	echo "Removing temporary branch..."
 	git checkout -
 	git branch -D gh-pages
@@ -59,7 +61,7 @@ cp -r website/other/* .
 if [[ $PUBLISH -eq 1 ]]; then
     echo "Sending files to remote..."
     git add --all
-    git commit -q -m "Publish $(date -I)" --no-gpg-sign
+    git commit -q -m "Publish $(date +%Y-%m-%d)" --no-gpg-sign
     git push -q -f --set-upstream origin gh-pages
 
     echo "Removing temporary branch..."
